### PR TITLE
chore(all): updated dependencies and build tasks to match nav skeletons, inc. karma/isparta"

### PR DESCRIPTION
**Pull request by chips5k**
Updated all dependencies and gulp tasks to match up with what is currently in https://github.com/aurelia/skeleton-navigation (skeleton-es2016).

This includes the recent updates to karma and the addition of isparta that are now in skeleton-nav.

Tested my changes with PhantomJS/Karma - no issues
Tested running all gulp tasks - no issues
Update: tested running karma via chrome on windows - no issues

### CODE REVIEW

**Comment by doktordirk** [comment]
i'd recommend to add the new test setup as seen in aurelia-metadata

**Comment by chips5k** [comment]
sure i will take a look over the next few days.

**Comment by EisenbergEffect** [comment]
@chips5k Thanks for the contribution! If you can update the test setup as @doktordirk recommends, that would be great and I'll be happy to merge this.

**Comment by chips5k** [comment]
@EisenbergEffect @doktordirk - modifications as per metadata repo, i hope this was what you meant :)
Tested on win10/chrome and c9/ubuntu/phantomjs successfully.

**Comment by doktordirk** [comment]
@chips5k 
yes. that'll work. you need to revert the change doc/changelog though. then i'll be happy

**Comment by doktordirk** [comment]
@chips5k oh, same for changed version number in package.json. need to revert that. version bumping isn't our job

**Comment by chips5k** [comment]
@doktordirk
Done, sorry i didn't realize they got changed, serves me right for blindly adding all.

p.s - is there a guide on what we should be entering into the scope e.g chore(<scope>) ? the contributing doc wasn't really specific with scope (sorry i'm learning).

**Comment by doktordirk** [comment]
@chips5k  hehe, no worries :) nice job

**Pull request merged**
